# Generated by Django 4.2 on 2023-07-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_image_id'),
        ('Gallery', '0002_alter_image_options_alter_image_id'),
    ]

    operations = [
    ]
