# Generated by Django 4.2 on 2023-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_message_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Message',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
