# Generated by Django 4.2 on 2023-08-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.CharField(default='Type here', max_length=255),
        ),
    ]
