# Generated by Django 4.2.1 on 2023-09-01 06:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='location',
            field=models.CharField(default='Type here', max_length=255),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='phone number', max_length=255, region=None),
        ),
    ]
