# Generated by Django 4.2 on 2023-08-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
